import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "womens-comfort-brief-1",
    name: "Women's Comfort Brief",
    description: "Ultra-soft cotton briefs designed for all-day comfort with a seamless finish.",
    price: 19.99,
    image: "/women1.jfif",
    category: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["black", "white", "nude"],
    brand: "Comfort Essentials",
    date: "2023-04-15",
  },
  {
    id: "mens-boxer-brief-1",
    name: "Men's Premium Boxer Brief",
    description: "Breathable boxer briefs with moisture-wicking technology for ultimate comfort.",
    price: 24.99,
    image: "/men1.jfif",
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "navy", "gray"],
    brand: "Urban Comfort",
    date: "2023-05-20",
  },
  {
    id: "womens-lace-thong-1",
    name: "Women's Lace Thong",
    description: "Delicate lace thong with a comfortable fit and elegant design.",
    price: 15.99,
    originalPrice: 22.99,
    image: "/women2.jfif",
    category: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["black", "red", "blue"],
    brand: "Elegance",
    sale: true,
    date: "2023-06-10",
  },
  {
    id: "mens-trunk-1",
    name: "Men's Athletic Trunk",
    description: "Performance trunks designed for active lifestyles with quick-dry fabric.",
    price: 22.99,
    image: "/men2.jfif",
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "blue", "red"],
    brand: "ActiveFit",
    date: "2023-07-05",
  },
  {
    id: "womens-bralette-1",
    name: "Women's Comfort Bralette",
    description: "Wireless bralette offering natural support and all-day comfort.",
    price: 29.99,
    image: "/women3.jfif",
    category: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["black", "white", "pink"],
    brand: "Comfort Essentials",
    date: "2023-08-12",
  },
  {
    id: "mens-brief-1",
    name: "Men's Classic Brief",
    description: "Traditional briefs made from premium cotton for everyday comfort.",
    price: 18.99,
    originalPrice: 24.99,
    image: "/men3.jfif",
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["white", "black", "gray"],
    brand: "Urban Comfort",
    sale: true,
    date: "2023-09-08",
  },
  {
    id: "womens-hipster-1",
    name: "Women's Cotton Hipster",
    description: "Mid-rise hipster panties with a comfortable cotton blend.",
    price: 16.99,
    image: "/images.jfif",
    category: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["black", "white", "blue"],
    brand: "Comfort Essentials",
    date: "2023-10-15",
  },
  {
    id: "mens-boxer-1",
    name: "Men's Relaxed Boxer",
    description: "Loose-fit boxers made from soft, breathable fabric for maximum comfort.",
    price: 21.99,
      image: "/men4.jfif",
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["plaid", "striped", "solid"],
    brand: "Urban Comfort",
    date: "2023-11-20",
  },
  {
    id: "womens-boyshort-1",
    name: "Women's Boyshort",
    description: "Full-coverage boyshorts with a comfortable waistband and no-ride design.",
    price: 17.99,
      image: "/women4.jpg",
    category: "women",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["black", "gray", "pink"],
    brand: "Elegance",
    date: "2023-12-05",
  },
  {
    id: "mens-performance-brief-1",
    name: "Men's Performance Brief",
    description: "Athletic briefs designed for sports and active lifestyles.",
    price: 26.99,
    originalPrice: 32.99,
      image: "/men5.jfif",
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "blue", "red"],
    brand: "ActiveFit",
    sale: true,
    date: "2024-01-10",
  },
  {
    id: "womens-seamless-thong-1",
    name: "Women's Seamless Thong",
    description: "Invisible under clothing with a smooth, seamless design.",
    price: 14.99,
      image: "/women5.jfif",
    category: "women",
    sizes: ["XS", "S", "M", "L"],
    colors: ["nude", "black", "white"],
    brand: "Elegance",
    date: "2024-02-15",
  },
  {
    id: "mens-long-boxer-1",
    name: "Men's Long Boxer Brief",
    description: "Extended leg boxer briefs for additional coverage and support.",
    price: 27.99,
      image: "/men1.jfif",
    category: "men",
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "gray", "navy"],
    brand: "ActiveFit",
    date: "2024-03-20",
  },
]
